#!/bin/bash

# add the following in .bashrc
#export BOOST_ROOT=/home/luyanqing/bin/boost_1_58_0
#export LD_LIBRARY_PATH=$BOOST_ROOT/stage/lib:$LD_LIBRARY_PATH

g++ -g $1 -o a -I $BOOST_ROOT -L$BOOST_ROOT/stage/lib -lboost_thread -lboost_system -lpthread 
